version: '3.8'
services:
  mysql:
    image: mysql
    container_name: dine-out-primary-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./prisma/data:/var/lib/mysql
  shadow-db:
    image: mysql
    container_name: dine-out-shadow-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shadow-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password