version: '3.8'
services:
  # dev-test-db:
  #   image: mysql:latest
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_DATABASE: 'test-db'
  #     MYSQL_USER: 'user'
  mysql:
    image: mysql
    container_name: dine-out-sql-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./prisma/data:/var/lib/mysql